name: Deploy Release

on:
  release:
    types: [published]

jobs:
  deploy_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Yarn
        run: npm install -g yarn 

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install Node.js dependencies
        run: yarn install
        env:
          NPM_CONFIG_USERCONFIG: .npmrc.ci
          NODE_AUTH_TOKEN: ${{ secrets.MASTER_PACKAGE_KEY }}

      - name: Create Build
        run: yarn build:web
        env:
          REACT_NATIVE_API_BASE_URL: https://prototype-release.rizefs.com
          ALLOW_SIGNUP: false
          SENTRY_DSN: https://c705c0b521f7456dabe5d9e4cd24f64d@o56811.ingest.sentry.io/5855434
          RIZE_ENV: release

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=web-build/ --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.RELEASE_NETLIFY_SITE_ID }}